name: Build Uncertain Voice APK

on:
  push:
    branches: [ "main", "master" ] # Jalankan setiap kali kamu save/commit
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Script
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle

    - name: Grant Execute Permission for Gradlew
      run: chmod +x gradlew

    - name: Build Debug APK
      run: ./gradlew assembleDebug

    - name: Upload APK Result
      uses: actions/upload-artifact@v4
      with:
        name: UncertainVoice-Debug
        path: app/build/outputs/apk/debug/app-debug.apk
        
